### ISSUE TITLE
Suggestion: detect when dark mode changes on the desktop

### ISSUE THREAD

**Issue by nicolasff** [paolosimone/virtual-json-viewer#18]
Hi Paolo,

I discovered this project in your response to my comment about JSON viewers yesterday, great job with this extension!

I've been using it for a little while today and noticed that while you already detect when the theme is changed in the options, the same doesn't happen when the system itself (the desktop really) switches modes. So changing the mode in the options applies the chosen theme immediately, but if you have "system" selected and the desktop itself switches, the theme doesn't change until the tab is reloaded.

Steps to reproduce:
1. Start with the OS desktop in "light mode"
2. In the options, select theme: "System theme"
3. Open a JSON file, it's light-themed as expected
4. Switch the desktop to "dark mode"
5. The JSON render only becomes dark if the tab is reloaded (this happens from dark to light as well, of course)

It seems like just adding a watcher function with `setInterval` to detect this would likely be enough, although I can't say I'm qualified enough to make recommendations on Chrome extensions :-)

This is clearly a pretty minor issue, but I figured that since you had already gone through the effort of applying the theme immediately using a storage event listener when the options are changed, you might want to have each page do the same when the desktop switches modes too.

**Comment by paolosimone** [comment]
Well, this is embarassing, I had my notification settings misconfigured so I found out about this issue just yesterday 😅

Sorry, let's reset.

---

Hi Nicola,

Thank you for actually use my extension!

I'm glad you liked it... and that the worst issue you found (or at least opened) was this one 😄 

> I figured that since you had already gone through the effort of applying the theme immediately using a storage event listener

Yeah, I might have been carried away just a liiitle too much. Too late to stop now, see if you like the solution in #21 

I'm planning a new patch release next week, so just wait a little longer and you'll have your killer feature!

**Comment by nicolasff** [comment]
Interesting to see the implementation with React! I've only used it a little bit so I'm not very familiar with it, although this led me to read about hooks and I can see how powerful this framework is.

I'm not so sure this is a killer feature 😄, but I'm looking forward to seeing what's in the new update.
