### ISSUE TITLE
Feature Request: Mouseless work by keyboard shortcuts

### ISSUE THREAD

**Issue by originalrusyn** [paolosimone/virtual-json-viewer#24]
Could you please define default keyboard shortcuts at least for
1. Expand All
2. Collapse All
3. Navigate To Next Array Element
4. Navigate To Previous Array Element
5. Expand/Collapse Current Element
6. Jump To JQ Filter TextBox
7. Scroll Up
8. Scroll Down
9. Switch To Raw View 
10. Switch To Tree View
11. Case Sensitive On/Off
12. Hide/Unhide mismatch

**Comment by paolosimone** [comment]
This is interesting but should be designed carefully. For instance we must avoid conflicts with the defaults browser shortcuts, but even then we could break some custom global shortcut the user have, maybe from other plugins. We could either add an option to disable shortcuts or even better allow the shortcuts to be configurable, but this second option increases the implementation effort...

I agree with that having some form of shortcut is better than having none, so I'll surely look into it when I have I little more spare time!

**Comment by paolosimone** [comment]
Shortcuts will be available in v0.2.0!

Complete list here: https://github.com/paolosimone/virtual-json-viewer#keyboard-shortcuts
