### ISSUE TITLE
[BUG] Huge errors cover the search bar

### ISSUE THREAD

**Issue by chrooti** [paolosimone/virtual-json-viewer#32]
### Buggy behavior
When an error is too big it (sometimes) ends up hiding the full search bar. (see attached screenshot)

### Expected behavior
It doesn't happen (they are output below the bar).

### Screenshot
![1669283063](https://user-images.githubusercontent.com/95884058/203752147-86e9c8e0-5e05-476c-932b-7a79a28169d3.png)

### Workaround
Reload the window.

**Comment by paolosimone** [comment]
I know 😔 Sometimes it happens even without errors (e.g. on window resize?), but I've not been able to reproduce it consistently and fix it...

**Comment by paolosimone** [comment]
close due to inactivity, feel free to open a new issue if the bug pops up again
