### ISSUE TITLE
Option to disable sorting. Display the JSON data as it is in tree view

### ISSUE THREAD

**Issue by SundaresanSelvaraj** [paolosimone/virtual-json-viewer#40]
Great experience with this extension so far. Currently, the extension sorts based on keys and displays as a tree view. Can you please consider providing an option to disable sorting?

**Comment by paolosimone** [comment]
Hi @SundaresanSelvaraj thank you for you feedback!

That's a reasonable request and fairly easy to implement (#41): it will be included in next release v1.0.6

For most cases should be fine, but be aware that this won't guarantee 100% that the order shown by the extension will be the same of the original json text as the output order will be dictated by javascript `Object.keys(JSON.parse(json))`

More info in the [FAQs](https://github.com/paolosimone/virtual-json-viewer#keys-order-is-not-preserved)

Hope you'll find it useful nonetheless
