### ISSUE TITLE
Enable the plugin on json content, regardless of content type

### ISSUE THREAD

**Issue by paolosimone** [paolosimone/virtual-json-viewer#50]
Request from @rvfet (original comment [here](https://github.com/paolosimone/virtual-json-viewer/pull/48#issuecomment-1817802864))

> Would be great if the extension could fallback to trying to parse the response into json even when content type does not match any json format, just as a last chance, it'd be a great addition. I'm aware that it'd create some performance bottlenecks since it'd need to check every page you visit but it could be an option that we can toggle, or perhaps manual wildcard/regex based custom website matching could help a ton, too.

**Comment by paolosimone** [comment]
@rvfet Thanks for the suggestion!

Agree on not making it the default behavior due to performance cost. Both proposed solutions would require to read application settings on (every) page load. I guess this is technically feasible and probably won't have a negative impact on browsing experience, but unfortunately _"read application settings before application is loaded"_ would require some not-so-small changes in the code.

In general it feels like a workaround, the real issue is that the server should always reply with a meaningful content type!

Given the effort/value I won't actively work on this at the moment... but I also know that in the real world there are a lot of servers over which we don't have control, so I'll leave this issue open for others to vote.

**Comment by nightpool** [comment]
@paolosimone What about adding a button or menu item that users could use to force the extension to load on pages where it didn't automatically fire? 

Right now the chrome button redirects to the settings page, but maybe if the content is JSON-parsable and it hasn't already been loaded it should load the virtual viewer instead

**Comment by paolosimone** [comment]
@RVFET @nightpool @fpiriz-inditex @hal-marcel Thanks everybody for your feedback!

In the next release (`1.2.0`) there will be an advanced opt-in setting to enable parsing the content on pages that match a user-provided regex, to handle cases when the content-type is not JSON ✅
